
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pay2bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest